version: '3.4'
services:
  controller-5000:
    network_mode: host
    image: controller-5000
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
        - ./:/usr/src/app
    environment:
      XML_RPC_PORT: 5000
      XML_RPC_IP: 'xxx.xxx.xxx.xxx'
      WEB_SOCKET_URL: 'ws://xxx.xxx.xxx.xxx:8080'
    expose:
      - 5000